#!/bin/bash

set -e
OUT="$1"

YARN=$(pwd)/node_modules/.bin/yarn

if [[ ! -x "${YARN}" ]]; then
    # Ensure any npm output goes to stderr and doesn't affect our
    # echo output below
    >&2 npm install yarn
fi

echo ${YARN} > ${OUT}
