#!/bin/bash

printf "\033[0;32mRunning tests...\033[0m\n"

# Pass lint and mocha tests
CHECK_OUTPUT=`make pre-commit`
if [ $? -ne 0 ]
then
	printf "%s\n" "${CHECK_OUTPUT}"
	printf "\033[0;31mAborting commit\033[0m\n"
	exit 1
fi

# Have normalized whitespaces
git diff-index --check --cached 'HEAD' --
if [ $? -ne 0 ]
then
    printf "\033[0;31mAborting commit\033[0m\n"
    exit 1
fi

printf "\033[0;32mTests pass!\033[0m\n"
