; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26504.0

	TITLE	C:\Source\compiler-explorer\test\cases\vc-regex-example.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

; only here to exercise bug https://github.com/mattgodbolt/compiler-explorer/issues/1337
1234

END
