//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35583870
// Cuda compilation tools, release 12.8, V12.8.93
// Based on NVVM 7.0.1
//

.version 8.7
.target sm_75
.address_size 64

	// .globl	_Z6kernelv
.extern .func  (.param .b32 func_retval0) vprintf
(
	.param .b64 vprintf_param_0,
	.param .b64 vprintf_param_1
)
;
.global .align 1 .b8 $str[13] = {104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 10};

.visible .entry _Z6kernelv()
{
	.reg .b32 	%r<2>;
	.reg .b64 	%rd<3>;
	.loc	1 3 0


	.loc	1 4 5
	mov.u64 	%rd1, $str;
	cvta.global.u64 	%rd2, %rd1;
	{ // callseq 0, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd2;
	.param .b64 param1;
	st.param.b64 	[param1+0], 0;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r1, [retval0+0];
	} // callseq 0
	.loc	1 5 1
	ret;

}

	.file	1 "/app/example.cu"