id=riscv-tt-elf-g++-sfpi
name=Tenstorrent SFPI (RISC-V 32-bit)
exe=${TT_METAL_HOME}/bin/riscv-tt-elf-g++
type=tenstorrent
lang=c++
env.TT_METAL_HOME=${TT_METAL_HOME}
defaultCompileFlags=-march=rv32imf -mabi=ilp32f -O2 -c -S -fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti
supportsLinker=false
syntaxHighlight=riscv
group=Tenstorrent
supportsCfg=true
supportsBinary=false
hasAssembler=true
compileTimeoutMs=30000
maxOutputSize=10485760
compilationStrategy=file
