# Amazon prod environment settings for CO2
compilers=&co2rustc
defaultCompiler=co2rustc-trunk

objdumper=/opt/compiler-explorer/gcc-16.1.0/bin/objdump
demangler=/opt/compiler-explorer/demanglers/rust/bin/rustfilt
demanglerArgs=--format=rust
binaryHideFuncRe=^(_.*|call_gmon_start|(de)?register_tm_clones|frame_dummy|.*@plt.*)$

group.co2rustc.compilers=co2rustc-trunk
group.co2rustc.compilerType=co2rustc
compiler.co2rustc-trunk.exe=/opt/compiler-explorer/co2-trunk/bin/co2rustc
compiler.co2rustc-trunk.name=co2rustc (trunk)
compiler.co2rustc-trunk.semver=(trunk)
compiler.co2rustc-trunk.isNightly=true

tools=co2miri:co2fmt
tools.co2miri.name=CO2 Miri
tools.co2miri.exe=/opt/compiler-explorer/co2-trunk/bin/co2miri
tools.co2miri.type=independent
tools.co2miri.class=co2miri-tool
tools.co2miri.stdinHint=disabled
tools.co2miri.options=--sysroot=/opt/compiler-explorer/co2-trunk/miri-sysroot
tools.co2fmt.name=co2fmt
tools.co2fmt.exe=/opt/compiler-explorer/co2-trunk/bin/co2fmt
tools.co2fmt.type=independent
tools.co2fmt.class=co2fmt-tool
tools.co2fmt.stdinHint=disabled
tools.co2fmt.options=--emit stdout
