# Default settings for CO2

objdumper=objdump
supportsBinary=true
supportsExecute=true
versionFlag=--version
demangler=c++filt
demanglerArgs=--format=rust
binaryHideFuncRe=^(_.*|call_gmon_start|(de)?register_tm_clones|frame_dummy|.*@plt.*)$

compilers=&co2rustc
defaultCompiler=co2rustc

group.co2rustc.compilers=co2rustc
group.co2rustc.compilerType=co2rustc
compiler.co2rustc.exe=/usr/bin/co2rustc
compiler.co2rustc.name=co2rustc

tools=co2miri:co2fmt
tools.co2miri.name=CO2 Miri
tools.co2miri.exe=/usr/bin/co2miri
tools.co2miri.type=independent
tools.co2miri.class=co2miri-tool
tools.co2miri.stdinHint=disabled
tools.co2fmt.name=co2fmt
tools.co2fmt.exe=/usr/bin/co2fmt
tools.co2fmt.type=independent
tools.co2fmt.class=co2fmt-tool
tools.co2fmt.stdinHint=disabled
tools.co2fmt.options=--emit stdout
