compilers=&nvcc
defaultCompiler=nvcc-default
demangler=undname.exe
demanglerType=win32
objdumper=dumpbin.exe
objdumperType=vc

group.nvcc.compilers=nvcc-default
group.nvcc.options=--keep-device-functions
group.nvcc.versionRe=^Cuda.*
group.nvcc.compilerType=nvcc-win32
group.nvcc.nvdisasm=nvdisasm.exe
group.nvcc.libpathFlag=-LIBPATH:
group.nvcc.rpathFlag=-LIBPATH:

compiler.nvcc-default.name=NVCC system
compiler.nvcc-default.exe=nvcc.exe
compiler.nvcc-default.alias=nvcc
compiler.nvcc-default.options=--keep-device-functions --use-local-env

tools=clangtidydefault

tools.clangtidydefault.exe=clang-tidy.exe
tools.clangtidydefault.name=clang-tidy (local)
tools.clangtidydefault.type=independent
tools.clangtidydefault.class=clang-tidy-tool
tools.clangtidydefault.stdinHint=disabled
