compilers=&doolang

group.doolang.compilers=doolang
group.doolang.isSemver=true
group.doolang.compilerType=doolang

compiler.doolang.exe=X:/Projects/doo/target-windows/release/doo.exe
compiler.doolang.name=Doolang (latest)
compiler.doolang.compilerType=doolang
compiler.doolang.supportsOptOutput=false
compiler.doolang.supportsAstView=false
compiler.doolang.supportsIrView=true
compiler.doolang.supportsFiltersInTool=false
