################################
# TODO: remove me
compilers=&e2k-flcc
defaultCompiler=e2k-flcc12916

################################
# MCST LCC for E2K
group.e2k-flcc.compilers=e2k-flcc11911:e2k-flcc12017:e2k-flcc12319:e2k-flcc12322:e2k-flcc12325:e2k-flcc12328:e2k-flcc12410:e2k-flcc12512:e2k-flcc12514:e2k-flcc12515:e2k-flcc12516:e2k-flcc12517:e2k-flcc12518:e2k-flcc12519:e2k-flcc12520:e2k-flcc12522:e2k-flcc12523:e2k-flcc12524:e2k-flcc12525:e2k-flcc12526:e2k-flcc12527:e2k-flcc12604:e2k-flcc12606:e2k-flcc12609:e2k-flcc12610:e2k-flcc12611:e2k-flcc12612:e2k-flcc12614:e2k-flcc12615:e2k-flcc12616:e2k-flcc12617:e2k-flcc12618:e2k-flcc12619:e2k-flcc12620:e2k-flcc12621:e2k-flcc12622:e2k-flcc12704:e2k-flcc12705:e2k-flcc12706:e2k-flcc12708:e2k-flcc12709:e2k-flcc12710:e2k-flcc12711:e2k-flcc12712:e2k-flcc12714:e2k-flcc12717:e2k-flcc12721:e2k-flcc12723:e2k-flcc12807:e2k-flcc12809:e2k-flcc12908:e2k-flcc12911:e2k-flcc12912:e2k-flcc12914:e2k-flcc12915:e2k-flcc12916
group.e2k-flcc.groupName=e2k mcst lcc
group.e2k-flcc.baseName=e2k lcc
group.e2k-flcc.instructionSet=e2k
group.e2k-flcc.isSemVer=true
group.e2k-flcc.supportsBinary=true
group.e2k-flcc.supportsBinaryObject=true
group.e2k-flcc.supportsExecute=true
group.e2k-flcc.emulated=true
group.e2k-flcc.executionWrapper=/opt/compiler-explorer/qemu-e2k/qemu-e2k-static
group.e2k-flcc.unwiseOptions=-march=native|-mtune=native
group.e2k-flcc.objdumper=/opt/compiler-explorer/lcc-1.29.16.e2k-v4.linux-6.1/bin.toolchain/e2k-linux-objdump
group.e2k-flcc.demangler=/opt/compiler-explorer/lcc-1.29.16.e2k-v4.linux-6.1/bin.toolchain/e2k-linux-c++filt
group.e2k-flcc.licenseLink=https://dev.mcst.ru/wp-content/uploads/2024/07/mit-license.pdf
group.e2k-flcc.licenseName=MIT License
group.e2k-flcc.licensePreamble=Copyright (c) 2024 AO "MCST"
group.e2k-flcc.compilerType=mcst-lcc-e2k
group.e2k-flcc.compilerCategories=mcst-lcc

compiler.e2k-flcc11911.exe=/opt/compiler-explorer/lcc-1.19.11.e2k-generic.2.6.33/bin/lfortran
compiler.e2k-flcc11911.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.19.11.e2k-generic.2.6.33/fs
compiler.e2k-flcc11911.semver=1.19.11
compiler.e2k-flcc11911.unwiseOptions=-mcpu=native
compiler.e2k-flcc11911.options=-mcpu=elbrus-v4

compiler.e2k-flcc12017.exe=/opt/compiler-explorer/lcc-1.20.17.e2k-generic.3.14/bin/lfortran
compiler.e2k-flcc12017.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.20.17.e2k-generic.3.14/fs
compiler.e2k-flcc12017.semver=1.20.17
compiler.e2k-flcc12017.unwiseOptions=-mcpu=native
# By default compiler generate code with -mcpu=generic but newer objdump does not understand such cpu.
compiler.e2k-flcc12017.options=-mcpu=elbrus-v4

compiler.e2k-flcc12319.exe=/opt/compiler-explorer/lcc-1.23.19.e2k-v4.4.9/bin/lfortran
compiler.e2k-flcc12319.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.23.19.e2k-v4.4.9/fs
compiler.e2k-flcc12319.semver=1.23.19
compiler.e2k-flcc12322.exe=/opt/compiler-explorer/lcc-1.23.22.e2k-v4.4.9/bin/lfortran
compiler.e2k-flcc12322.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.23.22.e2k-v4.4.9/fs
compiler.e2k-flcc12322.semver=1.23.22
compiler.e2k-flcc12325.exe=/opt/compiler-explorer/lcc-1.23.25.e2k-v4.4.9/bin/lfortran
compiler.e2k-flcc12325.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.23.25.e2k-v4.4.9/fs
compiler.e2k-flcc12325.semver=1.23.25
compiler.e2k-flcc12328.exe=/opt/compiler-explorer/lcc-1.23.28.e2k-v4.4.9/bin/lfortran
compiler.e2k-flcc12328.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.23.28.e2k-v4.4.9/fs
compiler.e2k-flcc12328.semver=1.23.28

compiler.e2k-flcc12410.exe=/opt/compiler-explorer/lcc-1.24.10.e2k-v4.4.19/bin/lfortran
compiler.e2k-flcc12410.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.24.10.e2k-v4.4.19/fs
compiler.e2k-flcc12410.semver=1.24.10

compiler.e2k-flcc12512.exe=/opt/compiler-explorer/lcc-1.25.12.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12512.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.12.e2k-v4.5.4/fs
compiler.e2k-flcc12512.semver=1.25.12
compiler.e2k-flcc12514.exe=/opt/compiler-explorer/lcc-1.25.14.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12514.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.14.e2k-v4.5.4/fs
compiler.e2k-flcc12514.semver=1.25.14
compiler.e2k-flcc12515.exe=/opt/compiler-explorer/lcc-1.25.15.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12515.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.15.e2k-v4.5.4/fs
compiler.e2k-flcc12515.semver=1.25.15
compiler.e2k-flcc12516.exe=/opt/compiler-explorer/lcc-1.25.16.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12516.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.16.e2k-v4.5.4/fs
compiler.e2k-flcc12516.semver=1.25.16
compiler.e2k-flcc12517.exe=/opt/compiler-explorer/lcc-1.25.17.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12517.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.17.e2k-v4.5.4/fs
compiler.e2k-flcc12517.semver=1.25.17
compiler.e2k-flcc12518.exe=/opt/compiler-explorer/lcc-1.25.18.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12518.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.18.e2k-v4.5.4/fs
compiler.e2k-flcc12518.semver=1.25.18
compiler.e2k-flcc12519.exe=/opt/compiler-explorer/lcc-1.25.19.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12519.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.19.e2k-v4.5.4/fs
compiler.e2k-flcc12519.semver=1.25.19
compiler.e2k-flcc12520.exe=/opt/compiler-explorer/lcc-1.25.20.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12520.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.20.e2k-v4.5.4/fs
compiler.e2k-flcc12520.semver=1.25.20
compiler.e2k-flcc12522.exe=/opt/compiler-explorer/lcc-1.25.22.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12522.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.22.e2k-v4.5.4/fs
compiler.e2k-flcc12522.semver=1.25.22
compiler.e2k-flcc12523.exe=/opt/compiler-explorer/lcc-1.25.23.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12523.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.23.e2k-v4.5.4/fs
compiler.e2k-flcc12523.semver=1.25.23
compiler.e2k-flcc12524.exe=/opt/compiler-explorer/lcc-1.25.24.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12524.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.24.e2k-v4.5.4/fs
compiler.e2k-flcc12524.semver=1.25.24
compiler.e2k-flcc12525.exe=/opt/compiler-explorer/lcc-1.25.25.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12525.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.25.e2k-v4.5.4/fs
compiler.e2k-flcc12525.semver=1.25.25
compiler.e2k-flcc12526.exe=/opt/compiler-explorer/lcc-1.25.26.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12526.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.26.e2k-v4.5.4/fs
compiler.e2k-flcc12526.semver=1.25.26
compiler.e2k-flcc12527.exe=/opt/compiler-explorer/lcc-1.25.27.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12527.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.25.27.e2k-v4.5.4/fs
compiler.e2k-flcc12527.semver=1.25.27

compiler.e2k-flcc12604.exe=/opt/compiler-explorer/lcc-1.26.04.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12604.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.04.e2k-v4.5.4/fs
compiler.e2k-flcc12604.semver=1.26.04
compiler.e2k-flcc12606.exe=/opt/compiler-explorer/lcc-1.26.06.e2k-v5.5.4/bin/lfortran
compiler.e2k-flcc12606.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.06.e2k-v5.5.4/fs
compiler.e2k-flcc12606.semver=1.26.06
compiler.e2k-flcc12609.exe=/opt/compiler-explorer/lcc-1.26.09.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12609.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.09.e2k-v4.5.4/fs
compiler.e2k-flcc12609.semver=1.26.09
compiler.e2k-flcc12610.exe=/opt/compiler-explorer/lcc-1.26.10.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12610.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.10.e2k-v4.5.4/fs
compiler.e2k-flcc12610.semver=1.26.10
compiler.e2k-flcc12611.exe=/opt/compiler-explorer/lcc-1.26.11.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12611.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.11.e2k-v4.5.4/fs
compiler.e2k-flcc12611.semver=1.26.11
compiler.e2k-flcc12612.exe=/opt/compiler-explorer/lcc-1.26.12.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12612.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.12.e2k-v4.5.4/fs
compiler.e2k-flcc12612.semver=1.26.12
compiler.e2k-flcc12614.exe=/opt/compiler-explorer/lcc-1.26.14.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12614.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.14.e2k-v4.5.4/fs
compiler.e2k-flcc12614.semver=1.26.14
compiler.e2k-flcc12615.exe=/opt/compiler-explorer/lcc-1.26.15.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12615.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.15.e2k-v4.5.4/fs
compiler.e2k-flcc12615.semver=1.26.15
compiler.e2k-flcc12616.exe=/opt/compiler-explorer/lcc-1.26.16.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12616.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.16.e2k-v4.5.4/fs
compiler.e2k-flcc12616.semver=1.26.16
compiler.e2k-flcc12617.exe=/opt/compiler-explorer/lcc-1.26.17.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12617.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.17.e2k-v4.5.4/fs
compiler.e2k-flcc12617.semver=1.26.17
compiler.e2k-flcc12618.exe=/opt/compiler-explorer/lcc-1.26.18.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12618.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.18.e2k-v4.5.4/fs
compiler.e2k-flcc12618.semver=1.26.18
compiler.e2k-flcc12619.exe=/opt/compiler-explorer/lcc-1.26.19.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12619.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.19.e2k-v4.5.4/fs
compiler.e2k-flcc12619.semver=1.26.19
compiler.e2k-flcc12620.exe=/opt/compiler-explorer/lcc-1.26.20.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12620.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.20.e2k-v4.5.4/fs
compiler.e2k-flcc12620.semver=1.26.20
compiler.e2k-flcc12621.exe=/opt/compiler-explorer/lcc-1.26.21.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12621.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.21.e2k-v4.5.4/fs
compiler.e2k-flcc12621.semver=1.26.21
compiler.e2k-flcc12622.exe=/opt/compiler-explorer/lcc-1.26.22.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12622.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.26.22.e2k-v4.5.4/fs
compiler.e2k-flcc12622.semver=1.26.22

compiler.e2k-flcc12704.exe=/opt/compiler-explorer/lcc-1.27.04.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12704.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.04.e2k-v4.5.4/fs
compiler.e2k-flcc12704.semver=1.27.04
compiler.e2k-flcc12705.exe=/opt/compiler-explorer/lcc-1.27.05.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12705.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.05.e2k-v4.5.4/fs
compiler.e2k-flcc12705.semver=1.27.05
compiler.e2k-flcc12706.exe=/opt/compiler-explorer/lcc-1.27.06.e2k-v4.5.4/bin/lfortran
compiler.e2k-flcc12706.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.06.e2k-v4.5.4/fs
compiler.e2k-flcc12706.semver=1.27.06
compiler.e2k-flcc12708.exe=/opt/compiler-explorer/lcc-1.27.08.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12708.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.08.e2k-v4.5.10/fs
compiler.e2k-flcc12708.semver=1.27.08
compiler.e2k-flcc12709.exe=/opt/compiler-explorer/lcc-1.27.09.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12709.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.09.e2k-v4.5.10/fs
compiler.e2k-flcc12709.semver=1.27.09
compiler.e2k-flcc12710.exe=/opt/compiler-explorer/lcc-1.27.10.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12710.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.10.e2k-v4.5.10/fs
compiler.e2k-flcc12710.semver=1.27.10
compiler.e2k-flcc12711.exe=/opt/compiler-explorer/lcc-1.27.11.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12711.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.11.e2k-v4.5.10/fs
compiler.e2k-flcc12711.semver=1.27.11
compiler.e2k-flcc12712.exe=/opt/compiler-explorer/lcc-1.27.12.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12712.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.12.e2k-v4.5.10/fs
compiler.e2k-flcc12712.semver=1.27.12
compiler.e2k-flcc12714.exe=/opt/compiler-explorer/lcc-1.27.14.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12714.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.14.e2k-v4.5.10/fs
compiler.e2k-flcc12714.semver=1.27.14
compiler.e2k-flcc12717.exe=/opt/compiler-explorer/lcc-1.27.17.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12717.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.17.e2k-v4.5.10/fs
compiler.e2k-flcc12717.semver=1.27.17
compiler.e2k-flcc12721.exe=/opt/compiler-explorer/lcc-1.27.21.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12721.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.21.e2k-v4.5.10/fs
compiler.e2k-flcc12721.semver=1.27.21
compiler.e2k-flcc12723.exe=/opt/compiler-explorer/lcc-1.27.23.e2k-v4.5.10/bin/lfortran
compiler.e2k-flcc12723.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.27.23.e2k-v4.5.10/fs
compiler.e2k-flcc12723.semver=1.27.23

compiler.e2k-flcc12807.exe=/opt/compiler-explorer/lcc-1.28.07.e2k-v4.6.1/bin/lfortran
compiler.e2k-flcc12807.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.28.07.e2k-v4.6.1/fs
compiler.e2k-flcc12807.semver=1.28.07
compiler.e2k-flcc12809.exe=/opt/compiler-explorer/lcc-1.28.09.e2k-v4.6.1/bin/lfortran
compiler.e2k-flcc12809.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.28.09.e2k-v4.6.1/fs
compiler.e2k-flcc12809.semver=1.28.09

compiler.e2k-flcc12908.exe=/opt/compiler-explorer/lcc-1.29.08.e2k-v4.8c.linux-6.1/bin/lfortran
compiler.e2k-flcc12908.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.29.08.e2k-v4.8c.linux-6.1/fs
compiler.e2k-flcc12908.semver=1.29.08
compiler.e2k-flcc12911.exe=/opt/compiler-explorer/lcc-1.29.11.e2k-v4.linux-6.1/bin/lfortran
compiler.e2k-flcc12911.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.29.11.e2k-v4.linux-6.1/fs
compiler.e2k-flcc12911.semver=1.29.11
compiler.e2k-flcc12912.exe=/opt/compiler-explorer/lcc-1.29.12.e2k-v4.linux-6.1/bin/lfortran
compiler.e2k-flcc12912.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.29.12.e2k-v4.linux-6.1/fs
compiler.e2k-flcc12912.semver=1.29.12
compiler.e2k-flcc12914.exe=/opt/compiler-explorer/lcc-1.29.14.e2k-v4.linux-6.1/bin/lfortran
compiler.e2k-flcc12914.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.29.14.e2k-v4.linux-6.1/fs
compiler.e2k-flcc12914.semver=1.29.14
compiler.e2k-flcc12915.exe=/opt/compiler-explorer/lcc-1.29.15.e2k-v4.linux-6.1/bin/lfortran
compiler.e2k-flcc12915.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.29.15.e2k-v4.linux-6.1/fs
compiler.e2k-flcc12915.semver=1.29.15
compiler.e2k-flcc12916.exe=/opt/compiler-explorer/lcc-1.29.16.e2k-v4.linux-6.1/bin/lfortran
compiler.e2k-flcc12916.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.29.16.e2k-v4.linux-6.1/fs
compiler.e2k-flcc12916.semver=1.29.16

# Do not forget to update variables to a newer lcc version:
#   group.e2k-flcc.objdumper
#   group.e2k-flcc.demangler
