compilers=&gleam-beam:&gleam-javascript
defaultCompiler=gleam1181beam

group.gleam-beam.compilers=gleam1181beam:gleam1170beam
group.gleam-beam.groupName=Gleam (BEAM)
group.gleam-beam.isSemVer=true
group.gleam-beam.baseName=Gleam
group.gleam-beam.compilerType=gleam
group.gleam-beam.envVars=ROOTDIR=/opt/compiler-explorer/erlang-28.1.1/lib/erlang:BINDIR=/opt/compiler-explorer/erlang-28.1.1/lib/erlang/erts-16.1.1/bin:EMU=beam:PROGNAME=erl:ESCRIPT_EMULATOR=/opt/compiler-explorer/erlang-28.1.1/lib/erlang/erts-16.1.1/bin/erlexec

group.gleam-javascript.compilers=gleam1181javascript:gleam1170javascript
group.gleam-javascript.groupName=Gleam (JavaScript)
group.gleam-javascript.isSemVer=true
group.gleam-javascript.baseName=Gleam
group.gleam-javascript.compilerType=gleam

compiler.gleam1181beam.name=Gleam 1.18.1 (BEAM)
compiler.gleam1181beam.exe=/opt/compiler-explorer/gleam-1.18.1/gleam
compiler.gleam1181beam.runtime=/opt/compiler-explorer/erlang-28.1.1/bin/erl
compiler.gleam1181beam.executionWrapper=/opt/compiler-explorer/erlang-28.1.1/bin/escript
compiler.gleam1181beam.instructionSet=beam
compiler.gleam1181beam.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleam1181beam.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleam1181beam.semver=1.18.1
compiler.gleam1181beam.supportsBinary=true
compiler.gleam1181beam.supportsExecute=true

compiler.gleam1181javascript.name=Gleam 1.18.1 (JavaScript)
compiler.gleam1181javascript.exe=/opt/compiler-explorer/gleam-1.18.1/gleam
compiler.gleam1181javascript.target=javascript
compiler.gleam1181javascript.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleam1181javascript.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleam1181javascript.semver=1.18.1
compiler.gleam1181javascript.supportsExecute=false

compiler.gleam1170beam.name=Gleam 1.17.0 (BEAM)
compiler.gleam1170beam.exe=/opt/compiler-explorer/gleam-1.17.0/gleam
compiler.gleam1170beam.runtime=/opt/compiler-explorer/erlang-28.1.1/bin/erl
compiler.gleam1170beam.executionWrapper=/opt/compiler-explorer/erlang-28.1.1/bin/escript
compiler.gleam1170beam.instructionSet=beam
compiler.gleam1170beam.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleam1170beam.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleam1170beam.semver=1.17.0
compiler.gleam1170beam.supportsBinary=true
compiler.gleam1170beam.supportsExecute=true

compiler.gleam1170javascript.name=Gleam 1.17.0 (JavaScript)
compiler.gleam1170javascript.exe=/opt/compiler-explorer/gleam-1.17.0/gleam
compiler.gleam1170javascript.target=javascript
compiler.gleam1170javascript.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleam1170javascript.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleam1170javascript.semver=1.17.0
compiler.gleam1170javascript.supportsExecute=false
