# Default settings for Gleam
compilers=&gleam-beam

versionFlag=--version
objdumper=

group.gleam-beam.compilers=gleamdefault
group.gleam-beam.groupName=Gleam (BEAM)
group.gleam-beam.isSemVer=true
group.gleam-beam.baseName=Gleam
group.gleam-beam.compilerType=gleam

compiler.gleamdefault.name=Gleam default
compiler.gleamdefault.exe=gleam
compiler.gleamdefault.runtime=erl
compiler.gleamdefault.executionWrapper=escript
compiler.gleamdefault.instructionSet=beam
compiler.gleamdefault.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleamdefault.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleamdefault.supportsBinary=true
compiler.gleamdefault.supportsExecute=true

defaultCompiler=gleamdefault
compilerType=gleam
demangler=
postProcess=
options=
needsMulti=false
