# Default settings for Gleam
compilers=&gleam-beam:&gleam-javascript

versionFlag=--version
objdumper=

group.gleam-beam.compilers=gleamdefault
group.gleam-beam.groupName=Gleam (BEAM)
group.gleam-beam.isSemVer=true
group.gleam-beam.baseName=Gleam
group.gleam-beam.compilerType=gleam
group.gleam-beam.envVars=ERL_FLAGS=+S 1 +SDcpu 1 +SDio 1

group.gleam-javascript.compilers=gleamjavascriptdefault
group.gleam-javascript.groupName=Gleam (JavaScript)
group.gleam-javascript.isSemVer=true
group.gleam-javascript.baseName=Gleam
group.gleam-javascript.compilerType=gleam

compiler.gleamdefault.name=Gleam default (BEAM)
compiler.gleamdefault.exe=gleam
compiler.gleamdefault.runtime=erl
compiler.gleamdefault.executionWrapper=escript
compiler.gleamdefault.instructionSet=beam
compiler.gleamdefault.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleamdefault.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleamdefault.supportsBinary=true
compiler.gleamdefault.supportsExecute=false

compiler.gleamjavascriptdefault.name=Gleam default (JavaScript)
compiler.gleamjavascriptdefault.exe=gleam
compiler.gleamjavascriptdefault.target=javascript
compiler.gleamjavascriptdefault.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleamjavascriptdefault.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleamjavascriptdefault.supportsExecute=false

defaultCompiler=gleamdefault
compilerType=gleam
demangler=
postProcess=
options=
needsMulti=false
