compilers=&gleam
defaultCompiler=gleambeam

group.gleam.compilers=gleambeam:gleamjavascript:gleam1170beam:gleam1170javascript
group.gleam.isSemVer=true
group.gleam.baseName=Gleam
group.gleam.compilerType=gleam

compiler.gleambeam.name=Gleam 1.18.1 (BEAM)
compiler.gleambeam.exe=/opt/compiler-explorer/gleam-1.18.1/gleam
compiler.gleambeam.runtime=/opt/compiler-explorer/erlang-28.1.1/bin/erl
compiler.gleambeam.executionWrapper=/opt/compiler-explorer/erlang-28.1.1/bin/escript
compiler.gleambeam.instructionSet=beam
compiler.gleambeam.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleambeam.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleambeam.semver=1.18.1
compiler.gleambeam.supportsBinary=true
compiler.gleambeam.supportsExecute=true

compiler.gleamjavascript.name=Gleam 1.18.1 (JavaScript)
compiler.gleamjavascript.exe=/opt/compiler-explorer/gleam-1.18.1/gleam
compiler.gleamjavascript.target=javascript
compiler.gleamjavascript.executionWrapper=/usr/bin/node
compiler.gleamjavascript.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleamjavascript.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleamjavascript.semver=1.18.1
compiler.gleamjavascript.supportsExecute=true

compiler.gleam1170beam.name=Gleam 1.17.0 (BEAM)
compiler.gleam1170beam.exe=/opt/compiler-explorer/gleam-1.17.0/gleam
compiler.gleam1170beam.runtime=/opt/compiler-explorer/erlang-28.1.1/bin/erl
compiler.gleam1170beam.executionWrapper=/opt/compiler-explorer/erlang-28.1.1/bin/escript
compiler.gleam1170beam.instructionSet=beam
compiler.gleam1170beam.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleam1170beam.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleam1170beam.semver=1.17.0
compiler.gleam1170beam.supportsBinary=true
compiler.gleam1170beam.supportsExecute=true

compiler.gleam1170javascript.name=Gleam 1.17.0 (JavaScript)
compiler.gleam1170javascript.exe=/opt/compiler-explorer/gleam-1.17.0/gleam
compiler.gleam1170javascript.target=javascript
compiler.gleam1170javascript.executionWrapper=/usr/bin/node
compiler.gleam1170javascript.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleam1170javascript.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleam1170javascript.semver=1.17.0
compiler.gleam1170javascript.supportsExecute=true
