# Default settings for Gleam
compilers=&gleam

versionFlag=--version
objdumper=

group.gleam.compilers=gleamdefault
group.gleam.isSemVer=true
group.gleam.baseName=Gleam
group.gleam.compilerType=gleam

compiler.gleamdefault.name=Gleam default (BEAM)
compiler.gleamdefault.exe=gleam
compiler.gleamdefault.runtime=erl
compiler.gleamdefault.executionWrapper=escript
compiler.gleamdefault.instructionSet=beam
compiler.gleamdefault.stdlib=/opt/compiler-explorer/gleam-stdlib-1.0.5
compiler.gleamdefault.versionRe=[0-9]+[.][0-9]+[.][0-9]+
compiler.gleamdefault.supportsBinary=true
compiler.gleamdefault.supportsExecute=true

defaultCompiler=gleamdefault
compilerType=gleam
demangler=
postProcess=
options=
needsMulti=false
