compilers=&glslang:shaderexplorer_glsl

defaultCompiler=glslang-validator-trunk
supportsBinary=false
compilerType=glsl
instructionSet=spirv

disassemblerPath=/opt/compiler-explorer/SPIRV-Tools-master/build/tools/spirv-dis

group.glslang.compilers=glslang-validator-trunk
compiler.glslang-validator-trunk.exe=/opt/compiler-explorer/glslang-trunk/glslangValidator
compiler.glslang-validator-trunk.name=glslang (trunk)

compiler.shaderexplorer_glsl.exe=/opt/compiler-explorer/shader-explorer-0.1.0/bin/shader_explorer
compiler.shaderexplorer_glsl.name=shader_explorer
compiler.shaderexplorer_glsl.compilerType=shader-explorer
compiler.shaderexplorer_glsl.versionFlag=--version
compiler.shaderexplorer_glsl.supportsBinary=false
compiler.shaderexplorer_glsl.supportsExecute=false
compiler.shaderexplorer_glsl.options=--lang glsl --target asm --no-color
