compilers=&glslang:shaderexplorer_glsl012

defaultCompiler=glslang-validator-trunk
supportsBinary=false
compilerType=glsl
instructionSet=spirv

disassemblerPath=/opt/compiler-explorer/SPIRV-Tools-master/build/tools/spirv-dis

group.glslang.compilers=glslang-validator-trunk
compiler.glslang-validator-trunk.exe=/opt/compiler-explorer/glslang-trunk/glslangValidator
compiler.glslang-validator-trunk.name=glslang (trunk)
compiler.glslang-validator-trunk.isNightly=true

compiler.shaderexplorer_glsl012.exe=/opt/compiler-explorer/shader-explorer-0.1.2/bin/shader_explorer
compiler.shaderexplorer_glsl012.name=shader_explorer 0.1.2
compiler.shaderexplorer_glsl012.compilerType=shader-explorer
compiler.shaderexplorer_glsl012.versionFlag=--version
compiler.shaderexplorer_glsl012.supportsBinary=false
compiler.shaderexplorer_glsl012.supportsExecute=false
compiler.shaderexplorer_glsl012.options=--lang glsl --target asm --no-color
