compilers=&lean
defaultCompiler=lean_4_29_1
compilerType=lean
supportsBinary=false
versionRe=^Lean \(version [^\n]+

group.lean.compilers=lean_4_29_1
group.lean.isSemVer=true
group.lean.baseName=Lean

compiler.lean_4_29_1.exe=/opt/compiler-explorer/lean-4.29.1/bin/lean
compiler.lean_4_29_1.semver=4.29.1
