compilers=&lua
defaultCompiler=lua550

group.lua.compilers=lua515:lua524:lua536:lua547:lua550
group.lua.isSemVer=true
group.lua.baseName=Lua
group.lua.groupName=Lua (PUC-Rio)
group.lua.compilerType=lua
group.lua.licenseLink=https://www.lua.org/license.html
group.lua.licenseName=MIT License
group.lua.licensePreamble=Copyright (C) 1994-2024 Lua.org, PUC-Rio.

compiler.lua515.semver=5.1.5
compiler.lua515.exe=/opt/compiler-explorer/lua-5.1.5/bin/luac
compiler.lua515.interpreter=/opt/compiler-explorer/lua-5.1.5/bin/lua
compiler.lua524.semver=5.2.4
compiler.lua524.exe=/opt/compiler-explorer/lua-5.2.4/bin/luac
compiler.lua524.interpreter=/opt/compiler-explorer/lua-5.2.4/bin/lua
compiler.lua536.semver=5.3.6
compiler.lua536.exe=/opt/compiler-explorer/lua-5.3.6/bin/luac
compiler.lua536.interpreter=/opt/compiler-explorer/lua-5.3.6/bin/lua
compiler.lua547.semver=5.4.7
compiler.lua547.exe=/opt/compiler-explorer/lua-5.4.7/bin/luac
compiler.lua547.interpreter=/opt/compiler-explorer/lua-5.4.7/bin/lua
compiler.lua550.semver=5.5.0
compiler.lua550.exe=/opt/compiler-explorer/lua-5.5.0/bin/luac
compiler.lua550.interpreter=/opt/compiler-explorer/lua-5.5.0/bin/lua

supportsBinary=false
supportsExecute=true
interpreted=true
compilerType=lua
