compilers=&apple_metal

group.apple_metal.compilers=metal_31
group.apple_metal.groupName=Apple Metal
group.apple_metal.compilerType=metal
group.apple_metal.isSemVer=true

compiler.metal_31.exe=Z:/compilers/metal-3.1/bin/metal.exe
compiler.metal_31.semver=3.1
compiler.metal_31.name=Metal 3.1
compiler.metal_31.options=-I Z:/compilers/metal-3.1/include/metal
