compilers=&nexium
defaultCompiler=nexium120
objdumper=/opt/compiler-explorer/gcc-13.1.0/bin/objdump
supportsBinary=true
supportsExecute=true
compilerType=nexium
versionFlag=version
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|.plt.*|.*@plt|_dl_relocate_static_pie)$

group.nexium.compilers=nexium120
group.nexium.groupName=Nexium
group.nexium.isSemVer=true
group.nexium.baseName=nx
group.nexium.licenseName=MIT License
group.nexium.licenseLink=https://github.com/Londopy/nexium/blob/main/LICENSE

compiler.nexium120.semver=1.2.0
compiler.nexium120.exe=/opt/compiler-explorer/nexium-1.2.0/nx
compiler.nexium120.name=nx 1.2.0
