compilers=&perl
instructionSet=perl

supportsBinary=false
compilerType=perl
versionFlag=-v

group.perl.compilers=perl5422:perl5421:perl5403:perl5385:perl5363:perl5343:perl5321:perl5303:perl5283:perl5263:perl5244:perl5224:perl5203:perl5184:perl5163:perl5144:perl5101:perl589
group.perl.isSemVer=true
group.perl.baseName=Perl
group.perl.groupName=Perl
group.perl.compilerType=perl

compiler.perl589.semver=5.8.9
compiler.perl589.exe=/opt/compiler-explorer/perl-5.8.9/bin/perl
compiler.perl5101.semver=5.10.1
compiler.perl5101.exe=/opt/compiler-explorer/perl-5.10.1/bin/perl
compiler.perl5144.semver=5.14.4
compiler.perl5144.exe=/opt/compiler-explorer/perl-5.14.4/bin/perl
compiler.perl5163.semver=5.16.3
compiler.perl5163.exe=/opt/compiler-explorer/perl-5.16.3/bin/perl
compiler.perl5184.semver=5.18.4
compiler.perl5184.exe=/opt/compiler-explorer/perl-5.18.4/bin/perl
compiler.perl5203.semver=5.20.3
compiler.perl5203.exe=/opt/compiler-explorer/perl-5.20.3/bin/perl
compiler.perl5224.semver=5.22.4
compiler.perl5224.exe=/opt/compiler-explorer/perl-5.22.4/bin/perl
compiler.perl5244.semver=5.24.4
compiler.perl5244.exe=/opt/compiler-explorer/perl-5.24.4/bin/perl
compiler.perl5263.semver=5.26.3
compiler.perl5263.exe=/opt/compiler-explorer/perl-5.26.3/bin/perl
compiler.perl5283.semver=5.28.3
compiler.perl5283.exe=/opt/compiler-explorer/perl-5.28.3/bin/perl
compiler.perl5303.semver=5.30.3
compiler.perl5303.exe=/opt/compiler-explorer/perl-5.30.3/bin/perl
compiler.perl5321.semver=5.32.1
compiler.perl5321.exe=/opt/compiler-explorer/perl-5.32.1/bin/perl
compiler.perl5343.semver=5.34.3
compiler.perl5343.exe=/opt/compiler-explorer/perl-5.34.3/bin/perl
compiler.perl5363.semver=5.36.3
compiler.perl5363.exe=/opt/compiler-explorer/perl-5.36.3/bin/perl
compiler.perl5385.semver=5.38.5
compiler.perl5385.exe=/opt/compiler-explorer/perl-5.38.5/bin/perl
compiler.perl5403.semver=5.40.3
compiler.perl5403.exe=/opt/compiler-explorer/perl-5.40.3/bin/perl
compiler.perl5421.semver=5.42.1
compiler.perl5421.exe=/opt/compiler-explorer/perl-5.42.1/bin/perl
compiler.perl5422.semver=5.42.2
compiler.perl5422.exe=/opt/compiler-explorer/perl-5.42.2/bin/perl

interpreted=true
supportsExecute=true
needsMulti=false
