compilers=&pony
defaultCompiler=p0670


group.pony.compilers=ponynightly:p0332:p0341:p0351:p0360:p0370:p0383:p0391:p0400:p0412:p0420:p0432:p0440:p0452:p0460:p0470:p0480:p0491:p0500:p0511:p0525:p0530:p0541:p0551:p0562:p0571:p05813:p0590:p0606:p0611:p0621:p0634:p0640:p0650:p0660:p0670
group.pony.compilerType=pony
group.pony.isSemVer=true
group.pony.baseName=ponyc
group.pony.licenseLink=https://github.com/ponylang/ponyc/blob/main/LICENSE
group.pony.licenseName=BSD 2-Clause "Simplified" License
group.pony.licensePreamble=Copyright (C) 2016-2020, The Pony Developers

compiler.p0670.exe=/opt/compiler-explorer/ponyc-0.67.0/bin/ponyc
compiler.p0670.semver=0.67.0
compiler.p0660.exe=/opt/compiler-explorer/ponyc-0.66.0/bin/ponyc
compiler.p0660.semver=0.66.0
compiler.p0650.exe=/opt/compiler-explorer/ponyc-0.65.0/bin/ponyc
compiler.p0650.semver=0.65.0
compiler.p0640.exe=/opt/compiler-explorer/ponyc-0.64.0/bin/ponyc
compiler.p0640.semver=0.64.0
compiler.p0634.exe=/opt/compiler-explorer/ponyc-0.63.4/bin/ponyc
compiler.p0634.semver=0.63.4
compiler.p0621.exe=/opt/compiler-explorer/ponyc-0.62.1/bin/ponyc
compiler.p0621.semver=0.62.1
compiler.p0611.exe=/opt/compiler-explorer/ponyc-0.61.1/bin/ponyc
compiler.p0611.semver=0.61.1
compiler.p0606.exe=/opt/compiler-explorer/ponyc-0.60.6/bin/ponyc
compiler.p0606.semver=0.60.6
compiler.p0590.exe=/opt/compiler-explorer/ponyc-0.59.0/bin/ponyc
compiler.p0590.semver=0.59.0
compiler.p05813.exe=/opt/compiler-explorer/ponyc-0.58.13/bin/ponyc
compiler.p05813.semver=0.58.13
compiler.p0571.exe=/opt/compiler-explorer/ponyc-0.57.1/bin/ponyc
compiler.p0571.semver=0.57.1
compiler.p0562.exe=/opt/compiler-explorer/ponyc-0.56.2/bin/ponyc
compiler.p0562.semver=0.56.2
compiler.p0551.exe=/opt/compiler-explorer/ponyc-0.55.1/bin/ponyc
compiler.p0551.semver=0.55.1
compiler.p0541.exe=/opt/compiler-explorer/ponyc-0.54.1/bin/ponyc
compiler.p0541.semver=0.54.1
compiler.p0530.exe=/opt/compiler-explorer/ponyc-0.53.0/bin/ponyc
compiler.p0530.semver=0.53.0
compiler.p0525.exe=/opt/compiler-explorer/ponyc-0.52.5/bin/ponyc
compiler.p0525.semver=0.52.5
compiler.p0511.exe=/opt/compiler-explorer/ponyc-0.51.1/bin/ponyc
compiler.p0511.semver=0.51.1
compiler.p0500.exe=/opt/compiler-explorer/ponyc-0.50.0/bin/ponyc
compiler.p0500.semver=0.50.0
compiler.p0491.exe=/opt/compiler-explorer/ponyc-0.49.1/bin/ponyc
compiler.p0491.semver=0.49.1
compiler.p0480.exe=/opt/compiler-explorer/ponyc-0.48.0/bin/ponyc
compiler.p0480.semver=0.48.0
compiler.p0470.exe=/opt/compiler-explorer/ponyc-0.47.0/bin/ponyc
compiler.p0470.semver=0.47.0
compiler.p0460.exe=/opt/compiler-explorer/ponyc-0.46.0/bin/ponyc
compiler.p0460.semver=0.46.0
compiler.p0452.exe=/opt/compiler-explorer/ponyc-0.45.2/bin/ponyc
compiler.p0452.semver=0.45.2
compiler.p0440.exe=/opt/compiler-explorer/ponyc-0.44.0/bin/ponyc
compiler.p0440.semver=0.44.0
compiler.p0432.exe=/opt/compiler-explorer/ponyc-0.43.2/bin/ponyc
compiler.p0432.semver=0.43.2
compiler.p0420.exe=/opt/compiler-explorer/ponyc-0.42.0/bin/ponyc
compiler.p0420.semver=0.42.0
compiler.p0412.exe=/opt/compiler-explorer/ponyc-0.41.2/bin/ponyc
compiler.p0412.semver=0.41.2
compiler.p0400.exe=/opt/compiler-explorer/ponyc-0.40.0/bin/ponyc
compiler.p0400.semver=0.40.0
compiler.p0391.exe=/opt/compiler-explorer/ponyc-0.39.1/bin/ponyc
compiler.p0391.semver=0.39.1
compiler.p0383.exe=/opt/compiler-explorer/ponyc-0.38.3/bin/ponyc
compiler.p0383.semver=0.38.3
compiler.p0370.exe=/opt/compiler-explorer/ponyc-0.37.0/bin/ponyc
compiler.p0370.semver=0.37.0
compiler.p0360.exe=/opt/compiler-explorer/ponyc-0.36.0/bin/ponyc
compiler.p0360.semver=0.36.0
compiler.p0351.exe=/opt/compiler-explorer/ponyc-0.35.1/bin/ponyc
compiler.p0351.semver=0.35.1
compiler.p0341.exe=/opt/compiler-explorer/ponyc-0.34.1/bin/ponyc
compiler.p0341.semver=0.34.1
compiler.p0332.exe=/opt/compiler-explorer/ponyc-0.33.2/bin/ponyc
compiler.p0332.semver=0.33.2
compiler.ponynightly.exe=/opt/compiler-explorer/ponyc-nightly/bin/ponyc
compiler.ponynightly.semver=nightly
