compilers=&razorforge
compilerType=razorforge
defaultCompiler=razorforge011
supportsBinary=false
supportsBinaryObject=false
supportsExecute=false
group.razorforge.compilers=razorforge010:razorforge011
group.razorforge.isSemVer=true
group.razorforge.baseName=razorforge

compiler.razorforge010.semver=0.1.0
compiler.razorforge010.exe=/opt/compiler-explorer/razorforge-0.1.0/RazorForge
compiler.razorforge011.semver=0.1.1
compiler.razorforge011.exe=/opt/compiler-explorer/razorforge-0.1.1/RazorForge