compilers=&razorforge
compilerType=razorforge
defaultCompiler=razorforge004
supportsBinary=false
supportsBinaryObject=false
supportsExecute=false
group.razorforge.compilers=razorforge004
group.razorforge.isSemVer=true
group.razorforge.baseName=razorforge

compiler.razorforge004.semver=0.0.4-alpha
compiler.razorforge004.exe=/opt/compiler-explorer/razorforge-0.0.4-alpha/RazorForge