compilers=razorforgedefault
compilerType=razorforge
defaultCompiler=razorforgedefault
supportsBinary=false
supportsBinaryObject=false
supportsExecute=false
compiler.razorforgedefault.name=RazorForge
compiler.razorforgedefault.exe=/opt/compiler-explorer/razorforge-0.2.0/RazorForge