################################
# TODO: remove me
compilers=&e2k-rust
defaultCompiler=e2k-rust1870
demangler=/opt/compiler-explorer/lcc-1.29.16.e2k-v4.linux-6.1/bin.toolchain/e2k-linux-c++filt

E2KDefaultTarget=e2kv4-unknown-linux-gnu
E2KLinker=/opt/compiler-explorer/lcc-1.29.16.e2k-v4.linux-6.1/bin/lcc

################################
# Rust for E2K
group.e2k-rust.compilers=e2k-rust1780:e2k-rust1870
group.e2k-rust.groupName=rust e2k
group.e2k-rust.baseName=rust e2k
group.e2k-rust.instructionSet=e2k
group.e2k-rust.isSemVer=true
group.e2k-rust.supportsBinary=true
group.e2k-rust.supportsBinaryObject=true
group.e2k-rust.supportsExecute=true
group.e2k-rust.emulated=true
group.e2k-rust.executionWrapper=/opt/compiler-explorer/qemu-e2k/qemu-e2k-static
group.e2k-rust.executionWrapperArgs=-L|/opt/compiler-explorer/lcc-1.29.16.e2k-v4.linux-6.1/fs
group.e2k-rust.unwiseOptions=-Ctarget-cpu=native|target-cpu=native
group.e2k-rust.objdumper=/opt/compiler-explorer/lcc-1.29.16.e2k-v4.linux-6.1/bin.toolchain/e2k-linux-objdump
group.e2k-rust.licenseLink=https://github.com/helce/rust/blob/master/COPYRIGHT
group.e2k-rust.licenseName=Dual-licensed under Apache 2.0 and MIT terms
group.e2k-rust.licensePreamble=Rust is licensed under the Apache License, Version 2.0 or the MIT license
group.e2k-rust.compilerType=rust-e2k
group.e2k-rust.compilerCategories=rust-e2k

compiler.e2k-rust1780.exe=/opt/compiler-explorer/e2k-rust-1.78.0/bin/rustc
compiler.e2k-rust1780.semver=1.78.0
compiler.e2k-rust1870.exe=/opt/compiler-explorer/e2k-rust-1.87.0/bin/rustc
compiler.e2k-rust1870.semver=1.87.0
