compilers=&salam
defaultCompiler=salam043

group.salam.compilers=salam043
group.salam.isSemVer=true
group.salam.baseName=Salam
group.salam.groupName=Salam x86-64
group.salam.compilerType=salam
group.salam.supportsBinary=true
group.salam.supportsBinaryObject=true
group.salam.supportsExecute=true
group.salam.versionFlag=version
group.salam.objdumper=/opt/compiler-explorer/gcc-14.2.0/bin/objdump
group.salam.licenseLink=https://github.com/SalamLang/Salam/blob/main/LICENSE
group.salam.licenseName=GPL-3.0

compiler.salam043.semver=0.4.3
compiler.salam043.name=Salam 0.4.3
compiler.salam043.exe=/opt/compiler-explorer/salam-0.4.3/salam
compiler.salam043.options=--stdlib-path=/opt/compiler-explorer/salam-0.4.3/std
