# Default settings for Tenstorrent SFPI C++

compilers=sfpi
defaultCompiler=sfpi
compilerType=sfpi
supportsBinary=false
supportsExecute=false
demangler=c++filt
objdumper=objdump

compiler.sfpi.name=SFPI Compiler (riscv-tt-elf-g++)
compiler.sfpi.exe=/usr/local/bin/riscv-tt-elf-g++
compiler.sfpi.alias=sfpi
compiler.sfpi.instructionSet=riscv64
compiler.sfpi.versionFlag=--version
