compilers=&sfpi
compilerType=sfpi
defaultCompiler=sfpi755
supportsBinary=false
supportsExecute=false

group.sfpi.compilers=sfpi755:sfpi754
group.sfpi.groupName=SFPI
group.sfpi.demangler=/opt/compiler-explorer/sfpi-7.55.0/compiler/bin/riscv-tt-elf-c++filt
group.sfpi.objdumper=/opt/compiler-explorer/sfpi-7.55.0/compiler/bin/riscv-tt-elf-objdump
group.sfpi.instructionSet=riscv64
group.sfpi.versionFlag=--version
group.sfpi.options=-O1

compiler.sfpi755.exe=/opt/compiler-explorer/sfpi-7.55.0/compiler/bin/riscv-tt-elf-g++
compiler.sfpi755.name=SFPI 7.55.0
compiler.sfpi755.alias=sfpi
