compilers=&defaultslangc:shaderexplorer_slang012

defaultCompiler=slangc_2026_8_1
supportsBinary=false
compilerType=slang
instructionSet=spirv

disassemblerPath=/opt/compiler-explorer/SPIRV-Tools-master/build/tools/spirv-dis

group.defaultslangc.compilers=slangc_2024_14_6:slangc_2025_2_2:slangc_2025_6_2:slangc_2025_12_1:slangc_2025_21_1:slangc_2026_2:slangc_2026_8_1
group.defaultslangc.versionFlag=-version

compiler.slangc_2024_14_6.exe=/opt/compiler-explorer/slang-2024.14.6/bin/slangc
compiler.slangc_2024_14_6.name=slangc 2024.14.6
compiler.slangc_2025_2_2.exe=/opt/compiler-explorer/slang-2025.2.2/bin/slangc
compiler.slangc_2025_2_2.name=slangc 2025.2.2
compiler.slangc_2025_6_2.exe=/opt/compiler-explorer/slang-2025.6.2/bin/slangc
compiler.slangc_2025_6_2.name=slangc 2025.6.2
compiler.slangc_2025_12_1.exe=/opt/compiler-explorer/slang-2025.12.1/bin/slangc
compiler.slangc_2025_12_1.name=slangc 2025.12.1
compiler.slangc_2025_21_1.exe=/opt/compiler-explorer/slang-2025.21.1/bin/slangc
compiler.slangc_2025_21_1.name=slangc 2025.21.1
compiler.slangc_2026_2.exe=/opt/compiler-explorer/slang-2026.2/bin/slangc
compiler.slangc_2026_2.name=slangc 2026.2
compiler.slangc_2026_8_1.exe=/opt/compiler-explorer/slang-2026.8.1/bin/slangc
compiler.slangc_2026_8_1.name=slangc 2026.8.1

compiler.shaderexplorer_slang012.exe=/opt/compiler-explorer/shader-explorer-0.1.2/bin/shader_explorer
compiler.shaderexplorer_slang012.name=shader_explorer 0.1.2
compiler.shaderexplorer_slang012.compilerType=shader-explorer
compiler.shaderexplorer_slang012.versionFlag=--version
compiler.shaderexplorer_slang012.supportsBinary=false
compiler.shaderexplorer_slang012.supportsExecute=false
compiler.shaderexplorer_slang012.options=--lang slang --target asm --no-color
