compilers=&resolc
compilerType=resolc
defaultCompiler=resolc130_yul
supportsLibraryCodeFilter=true

group.resolc.compilers=resolc130_yul
group.resolc.compilerType=resolc
group.resolc.objdumper=/opt/compiler-explorer/clang-21.1.0/bin/llvm-objdump
group.resolc.objdumperType=llvm
group.resolc.isSemver=true
group.resolc.versionFlag=--version
group.resolc.intelAsm=false
group.resolc.supportsBinaryObject=true
group.resolc.supportsBinary=false
group.resolc.supportsExecute=false
group.resolc.instructionSet=riscv64
compiler.resolc130_yul.exe=/opt/compiler-explorer/resolc-1.3.0/resolc
compiler.resolc130_yul.semver=1.3.0
compiler.resolc130_yul.name=resolc 1.3.0

#################################
#################################
# Installed libs (See c++.amazon.properties for a scheme of libs group)
