name: Lint GitHub Actions workflows

on:
  push:
    branches: [main]
    paths: ['.github/workflows/**', '.github/actionlint.yaml']
  pull_request:
    paths: ['.github/workflows/**', '.github/actionlint.yaml']

permissions:
  contents: read

jobs:
  actionlint:
    if: github.repository_owner == 'compiler-explorer'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color
